{
 "title": "Admin Log",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "player",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n  bucket: \"${server}\",\n  tag: \"player\",\n  predicate: (r) => true,\n  start: -1y\n)"
   },
   { "name": "server", "query": "serverstats" }
  ]
 },
 "panels": [
  {
   "title": "item log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${server}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"playerloginv\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"player\"] == \"${player}\")\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "item log all",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${server}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"playerloginv\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "command log",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"${server}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"playerlog\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"player\"] == \"${player}\")\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "command log all",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"${server}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"playerlog\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Creative block break",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"${server}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"playerlogcrbreak\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"player\"] == \"${player}\")\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Creative block break all",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"${server}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"playerlogcrbreak\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Creative block place",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "query": "from(bucket: \"${server}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"playerlogcrplace\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"player\"] == \"${player}\")\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Creative block place all",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "query": "from(bucket: \"${server}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"playerlogcrplace\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}